Kategorie-Auswahl funktioniert nicht hierarisch
learnweb/moodle-tool_lifecycle pull request #137
Opened 2021-12-07 15:56 UTC by sus16cn

man konnte nur eine toplevel Kategorie auswählen, aber keine tieferen Kategorieebenen

2021-12-08 16:16 UTC, justusdieckmann requested changes
Hey,
danke für die PR. Man kann derzeit durchaus "Kinderkategorien" auswählen, allerdings werden diese nicht mit ihren Elternkategorien im Dropdown angezeigt, dementsprechend ist die PR eine schöne visuelle Verbesserung. Dankeschön!
Könntest du noch die zwei genannten Punkte fixen?
Viele Grüße
Justus

2021-12-08 16:16 UTC, justusdieckmann commented on trigger/categories/lib.php
> +        //}
Den auskommentierten Code bitte löschen. Die Zeile 120 ist dann auch überflüssig, richtig?

2021-12-08 16:16 UTC, justusdieckmann commented on trigger/categories/lib.php
> +        //Cangelog: Added core course lookup functionality, with flat hierachical representation
Nur was winziges, aber ich würde keinen Changelog als Kommentar in den Code schreiben, sondern eher einfach beschreiben, was die neue Zeile macht ('Get course categories with flat hierachical representation.', oder so)

Der [CI-Workflow](https://github.com/learnweb/moodle-tool_lifecycle/runs/4459602709?check_suite_focus=true#step:13:37) schlägt gerade auch wegen dem [Moodle Codestyle bei Kommentaren](https://docs.moodle.org/dev/Coding_style#Inline_comments) fehl

2022-01-06 09:06 UTC, Laur0r commented
@sus16cn any updates here? Looks good!

2022-02-14 20:47 UTC, justusdieckmann commented
I merged #140 which was submitted and adds the same feature, since it was passing the CI. Still, thank you for you contribution!

2022-02-14 20:47 UTC, closed without merging